### ISSUE TITLE
Python basic_api.py

### ISSUE THREAD

**Issue by dong-hub-png** [DerrickXuNu/Learn-Carla#2]
请问报这种错是什么原因造成的：destroying actors
done.
Traceback (most recent call last):
  File “basic_api.py", line 93, in <module>
    main()
  File "“basic_api.py", line 31, in main
    ego_vehicle_bp = blueprint_library.find('vehicle.mercedes-benz.coupe')
IndexError: blueprint 'vehicle.mercedes-benz.coupe' not found

**Comment by DerrickXuNu** [comment]
应该是版本问题，我这个支持到0911
